#!/usr/bin/env python

# Copyright (c) 2019 Computer Vision Center (CVC) at the Universitat Autonoma de
# Barcelona (UAB).
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.

import glob
import os
import sys
import threading
import numpy as np
import rclpy
from rclpy.node import Node
from cv_bridge import CvBridge
from sensor_msgs.msg import Image
import carla
import random
import time
from datetime import datetime
import cv2 as cv
from rclpy.executors import MultiThreadedExecutor
import csv
import argparse
import math


def main():
    
    
   
    # In this tutorial script, we are going to add a vehicle to the simulation
    # and let it drive in autopilot. We will also create a camera attached to
    # that vehicle, and save all the images generated by the camera to disk.

    try:
        # First of all, we need to create the client that will send the requests
        # to the simulator. Here we'll assume the simulator is accepting
        # requests in the localhost at port 2000.
        client = carla.Client('localhost', 2000)
        client.set_timeout(10.0)

        world = client.get_world()

        while True:
            for vehicle in world.get_actors().filter('vehicle.*'):
                print(vehicle.attributes.get('role_name'))
                time.sleep(1)
    except KeyboardInterrupt:
        print('Done')
        
    


if __name__ == '__main__':

    main()

    
